### ISSUE TITLE
Push docker images

### ISSUE THREAD

**Issue by will-molloy** [will-molloy/file-sync#10]
Via GitHub action

**Comment by will-molloy** [comment]
Workflow: https://github.com/will-molloy/file-backup/blob/main/.github/workflows/docker.yml

Jib: https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin

**Comment by jiyeonmolloy** [comment]
Thank you, creating a service account on Docker Hub 🐳 
username is: tobyhousesvc
repository: wilmol

**Comment by jiyeonmolloy** [comment]
https://www.baeldung.com/jib-dockerizing
